const STATES = {
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  FL: 'Florida',
  GA: 'Georgia',
  IL: 'Illinois',
  IN: 'Indiana',
  LA: 'Louisiana',
  MA: 'Massachusetts',
  MI: 'Michigan',
  NJ: 'New Jersey',
  NY: 'New York',
  OH: 'Ohio',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  SC: 'South Carolina',
  TX: 'Texas',
  VA: 'Virginia',
  VT: 'Vermont',
  WA: 'Washington',
  WI: 'Wisconsin',
};

export default STATES;
